#.travis.yml

language: node_js
node_js:
  - "node"

branches:
  only:
    - master

before_install:
  - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
  - npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_TOKEN

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod  --optimization=false

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    recipients:
      - john.baueriii@gmail.com
    on_failure: always
    on_success: always